version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
     - common
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/public
    depends_on:
      - webserver

  webserver:
    build:
      context: ./docker/webserver
      dockerfile: Dockerfile
    image: webserver:latest
    container_name: webserver
    restart: always
    ports:
      - "80"
    networks:
     - common
    working_dir: /var/www
    volumes:
      - ./docker/webserver/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/webserver/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/webserver/ports.conf:/etc/apache2/ports.conf
      - .:/var/www
    environment:
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
     - common
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  common:
    driver: bridge